# https://docs.docker.com/go/compose-spec-reference/

# For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose

services:
  redis:
    image: redis:latest
    hostname: redis

  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    ports:
      - 8000:8000

