/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Basic_3d_scene: typeof import('./src/components/basic_3d_scene.vue')['default']
    Fft_example_scene: typeof import('./src/components/fft_example_scene.vue')['default']
    Light_example_scene: typeof import('./src/components/light_example_scene.vue')['default']
  }
}
